### ISSUE TITLE
Getting error while running `npm run render`

### ISSUE THREAD

**Issue by preetb123** [airbnb/react-sketchapp#149] opened 2017-07-11 09:27 UTC
`$ npm run render`

> basic-setup@1.0.0 render /Users/preetam/Documents/rn-practice/react-sketchapp/examples/basic-setup
> skpm build --watch --run

(node:13338) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'apply' of undefined
(node:13338) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
🖨  Copied src/manifest.json in 856ms

**Comment by mathieudutour** [comment] 2017-07-11 09:41
I think it's a duplicate of https://github.com/airbnb/react-sketchapp/issues/138 and has been fixed with skpm@0.10.1

**Comment by namKolo** [comment] 2017-09-23 04:13
Hi @mathieudutour , I installed skpm@0.10.5. But I still got the same error when running `npm run  render`. Do you face to this issue?
My sketch version is `46.2`,  node is `6.9.x`, npm is `3.10.8`.

![image](https://user-images.githubusercontent.com/16164170/30769989-068c26cc-a050-11e7-9ac7-39d016101d95.png)

**Comment by namKolo** [comment] 2017-09-23 08:16
@mathieudutour Yah sorry, that was my bad. I found the reason why and fixed. Now it runs well.

**Closed** 2017-09-23 08:17 UTC
