### ISSUE TITLE
Sketch 44

### ISSUE THREAD

**Issue by richattack** [airbnb/react-sketchapp#102] opened 2017-05-18 18:42 UTC
_I am..._ attempting to run `npm run render` on the examples, using Sketch version 44. It fails with 

```Error while running the command after build```

`npm run build` and `npm run link-plugin` still appear to be working fine.

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:** `npm run render` to produce a Sketch file of rendered React components.

**Observed behavior:** ```*error* Error while running the command after build```

**How to reproduce:** 
1. Clone `react-sketchapp`
2. cd into the examples/foursquare-maps example. `npm install`
3. Run `npm run render`
4. Receive __error__ Error while running the command after build

**Sketch version:** 44 (new version as of this morning 5/18/2017)

**Please attach screenshots, a zip file of your project, and/or a link to your github project**
![screen shot 2017-05-18 at 2 41 29 pm](https://cloud.githubusercontent.com/assets/755288/26218193/1f749548-3bd8-11e7-9f46-04846a52a102.png)

**Comment by jongold** [comment] 2017-05-18 18:49
Thanks for reporting - closing this because it's a duplicate of #72 — I'm working on a fix 😭

**Closed by jongold** 2017-05-18 18:49 UTC

**Comment by hanserino** [comment] 2017-06-08 13:45
Any updates on this? Has this been resolved?
