### ISSUE TITLE
Error: Cannot render into Symbols page

### ISSUE THREAD

**Issue by LincMitch** [airbnb/react-sketchapp#362] opened 2018-06-21 12:07 UTC
I am unable to get the **Symbols** example to work. The Error: **Cannot render into Symbols page**
Takes me to these comments in the code:
```
// The Symbols page holds a special meaning within Sketch / react-sketchapp
// and due to how `makeSymbol` works, we cannot render into it
```

**Comment by jaridmargolin** [comment] 2018-06-21 15:42
Hi @LincMitch, this is a duplicate of #351. We just need get a new release out. In the future, I will keep issues open until they have been published. Landing in master isn't enough.

cc @mathieudutour

**Closed by jaridmargolin** 2018-06-21 15:42 UTC

**Comment by mathieudutour** [comment] 2018-06-21 15:48
can you prepare the release? update the package.json, update the changelog, etc
