### ISSUE TITLE
Error while running `npm run render` for `basic-setup` example

### ISSUE THREAD

**Issue by chrismanderson** [airbnb/react-sketchapp#155] opened 2017-07-19 14:41 UTC
_I am..._

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**
I should be able to build and run the basic-setup example in the repo when using the latest master commit (8633375).

**Observed behavior:**
When I run `npm run render` with a blank Sketch document open, I get the error 

```
Warning: Failed prop type: Invalid prop `error` supplied to `RedBox`.
    in RedBox
Struct CGRect has no member named size
```

**How to reproduce:**
```
git clone https://github.com/airbnb/react-sketchapp.git
cd examples/basic-setup
npm install
npm run render
```

**Sketch version:**
45.2

**Other notes**
I can build the `colors` example project correctly.

**Comment by mathieudutour** [comment] 2017-07-19 15:05
duplicate of #141?

**Comment by chrismanderson** [comment] 2017-07-19 15:18
Does look like the same issue, but I'm not running High Sierra so I figured was worth opening a separate issue.

That issue links to the [docs](http://airbnb.io/react-sketchapp/) that say there is a bug with Sketch v45, but the [readme](https://github.com/airbnb/react-sketchapp/blob/master/README.md) says v45 is supported so I don't know who to believe 😃 .

**Comment by jongold** [comment] 2017-07-19 17:04
My bad, forgot to republish the documentation site - fixing now

**Comment by qmolee** [comment] 2017-08-10 02:27
Same question ..😔ver.46 is supported?

**Comment by ianhook** [comment] 2017-08-10 21:29
@qmolee I was able to get everything to work when I remembered to run `npm install link-plugin`. I was not able to find the `CGRect` error that was mentioned in the original post.  Can you give more information on the problem you're seeing?

**Comment by mathieudutour** [comment] 2017-08-10 21:30
i think it was fixed in a more recent sketch version (saw that in the release notes, but don't remember which one)

**Comment by sibelius** [comment] 2017-10-13 11:24
same error here

Warning: Failed prop type: Invalid prop `error` supplied to `RedBox`.
    in RedBox
Struct CGRect has no member named size

Sketch 43.1 (39012)

**Comment by mathieudutour** [comment] 2017-10-13 11:26
> fixed in a more recent sketch version

**Comment by sibelius** [comment] 2017-10-13 11:31
fixed on Sketch 47

**Closed** 2017-10-14 07:25 UTC
