### ISSUE TITLE
how to rotate a 'View'?

### ISSUE THREAD

**Issue by dwb1994** [airbnb/react-sketchapp#326] opened 2018-05-14 03:36 UTC
I want to rotate a 'View' to 180°

I have tried 'transform' but it didn't work ... 🤔

Sketch version:48.2

**Comment by mathieudutour** [comment] 2018-05-14 14:09
It's not possible yet. I'm going to close this as it is a duplicate of https://github.com/airbnb/react-sketchapp/issues/14

**Closed by mathieudutour** 2018-05-14 14:09 UTC
