### ISSUE TITLE
react-sketchapp on npm gives error when used with yarn workspaces

### ISSUE THREAD

**Issue by peterpine83** [airbnb/react-sketchapp#281] opened 2018-03-10 20:21 UTC
I am reporting an issue using yarn workspaces and react-sketchapp. The version on npm still has `"yoga-layout": "1.6.0"`, which is causing the react-sketchapp to not work in my monorepo yarn workspaces project. 

related issue #241 

**Expected behavior:**
    react-sketchapp to install with version`"yoga-layout": "1.8.0"`

**Observed behavior:**
    react-sketchapp installs with version`"yoga-layout": "1.6.0"`
and I am getting: TypeError: {} is not a function. (In '{}("")', '{}' is an instance of Object)

**How to reproduce:**
Install react-sketchapp using yarn workspaces in a monorepo

**Sketch version:**
49

**Comment by mathieudutour** [comment] 2018-03-11 07:21
duplicate of #241

**Closed by mathieudutour** 2018-03-11 07:21 UTC
